### PR TITLE
Make a logo suggestion

### PR DESCRIPTION
**Pull request by jgorset**
I played around with @thuygianguyen's amazing logo kit and @zenangst's idea to make libraries just a single item instead of a stack. This isn't done or anything, but to follow up on the discussion in #5 it could be the start of something.

Example

### CODE REVIEW

**Comment by jgorset** [comment]
Not sure what we should do about the Photoshop files. They're kinda large and I'd rather not version control a 20+ megabyte file for every iteration of something. What do ya'll think, @hyperoslo/owners?

**Comment by thuyranosaurus** [comment]
If you just delete all the themes inside I think you'll shrink the file dramatically. But then again it is still Photoshop where filesizes are HUGE compared to Sketch. However, Sketch doesn't handle transforming and distorting as well as Photoshop.

**Comment by thuyranosaurus** [comment]
The single layer simply doesn't work on it's own I think

**Comment by jgorset** [comment]
Yeah it's a bit weird.

**Comment by zenangst** [comment]
logo 3

**Comment by jgorset** [comment]
That's pretty awesome. How do you like that with the single layer, @thuygianguyen?

**Comment by zenangst** [comment]
I added a little bit of perspective to it so that it's not all flat.

screen shot 2015-03-15 at 13 55 28

**Comment by thuyranosaurus** [comment]
It kinda seems stretched and oddshaped. How about keeping the three but making the bottom two ones Translucent'ish?

-Thuy Gia Nguyen

Designer & Team Leader

 977 35 583

 thuy@hyper.no

**Comment by zenangst** [comment]
Oh I like that thought.

**Comment by zenangst** [comment]
scatter

**Comment by zenangst** [comment]
logo 3

**Comment by jgorset** [comment]
Liking this a lot.

**Comment by zenangst** [comment]
I know that @RamonGilabert wants to take a shot at this, it's gonna be exciting to see what he comes up with.

**Comment by thuyranosaurus** [comment]
Is there enough dots on this. Doesn't look scattered at all. Kinda looks like a dice? 

-Thuy Gia Nguyen

Designer & Team Leader

 977 35 583

 thuy@hyper.no

**Comment by zenangst** [comment]
@thuygianguyen excellent point!

**Comment by thuyranosaurus** [comment]
Do you remember that part in that Apple ad about design? The one @RamonGilabert Totally ripped ;) there is a scene where all the dots explode. Is that a good scattering?

-Thuy Gia Nguyen

Designer & Team Leader

 977 35 583

 thuy@hyper.no

**Comment by zenangst** [comment]
with joy

Like this?

**Comment by RamonGilabert** [comment]
At 5 I get home and I'll start to work on it! :P

**Comment by thuyranosaurus** [comment]
Yeah! I def feel that's more of a scatter

-Thuy Gia Nguyen

Designer & Team Leader

 977 35 583

 thuy@hyper.no

**Comment by 3lvis** [comment]
It's so awesome to have you here @thuygianguyen, I wish you're the first of many designers to join this party.

**Comment by thuyranosaurus** [comment]
Awesome to be here and get inspired by the energy and devotion you guys have got going on in your team. And even more fun when you guys talk design :)

-Thuy Gia Nguyen

Designer & Team Leader

 977 35 583

 thuy@hyper.no

**Comment by aresundnes** [comment]
Not sure why, but I'm here too! Such email!Looking great though ;)

**Comment by jgorset** [comment]
Haha, hi @aresundnes! You can opt out of e-mails if you want (I have), by the way.

**Comment by RamonGilabert** [comment]
first

First MVP! I think less bubbles would be nicer, and the background color maybe!

**Comment by jgorset** [comment]
That's so different and so beautiful. The shape makes it look like an app, though. Maybe that's okay, but it's very different from the stack design of Form.

**Comment by jgorset** [comment]
How does it look on the stack?

**Comment by RamonGilabert** [comment]
Thank's @jgorset, I thought that would be like the main image, and then create a bigger image for the header, with: Made by hyper with love!

**Comment by RamonGilabert** [comment]
second

Or maybe this one as @thuygianguyen suggested! I was thinking the same! :D

**Comment by RamonGilabert** [comment]
fourth
third

@jgorset like this! :dancer: we could even put a gif made with Framer! 

Edit: Oh rightttt I got what you mean! I'll try a Form style!

**Comment by zenangst** [comment]
logo-more-scatter

I continued to iterate over the thing that I had and applied more scatter.

**Comment by thuyranosaurus** [comment]
I know my suggestion is somewhat cheesy, but it kinda works :)
screen shot 2015-03-15 at 19 19 07

**Comment by zenangst** [comment]
@thuygianguyen cheeses!... but should we drop multiple stacks when making a library icon?

**Comment by jgorset** [comment]
Hahaha, oh @thuygianguyen.

**Comment by thuyranosaurus** [comment]
@zenangst But the cheese is floating in mid air. I went for the low fat cheese.

**Comment by thuyranosaurus** [comment]
Would be really fun to make Libraries that represents ham, slice of bread and lettuce. Then we could release some sort of sandwitch bundle

**Comment by 3lvis** [comment]
Hahaha, loving the cheese

**Comment by zenangst** [comment]
@thuygianguyen: I like it, skeuomorphism 2.0: obscurism.

**Comment by akamphaug** [comment]
I think the shadow in @thuygianguyen  latest example makes it the single layer seem more "right". And the cutouts in the cheese further strengthens the "rightness" of the single layer since it connects the shadow and layer together.. Would love to see @zenangst s example with a shadow like that.

**Comment by thuyranosaurus** [comment]
Whoohoo! Andeas is here!

-Thuy Gia Nguyen

Designer & Team Leader

 977 35 583

 thuy@hyper.no

**Comment by zenangst** [comment]
@akamphaug Welcome to GitHub! I'll make another iteration and see where that takes us!

**Comment by tabishfayyaz** [comment]
I like @zenangst logo the most as its accurately illustrative of what the piece of code does

**Comment by thuyranosaurus** [comment]
@Tabish. In Norway everything is best described with Jarlsberg cheese. Have a bug in your code? Whip out a wheel of cheese! Just kidding! 

-Thuy Gia Nguyen

Designer & Team Leader

 977 35 583

 thuy@hyper.no

**Comment by zenangst** [comment]
scatter-new-version

What do you guys think about this one?

**Comment by thuyranosaurus** [comment]
How about adding some bookeh effect on that? Also. I think it looks better if you place the shadow further down, on the third plate (that is now gone). It gives it a better floaty feeling, and aldo we can use the logos together as they will be the same size

-Thuy Gia Nguyen

Designer & Team Leader

 977 35 583

 thuy@hyper.no

**Comment by timkurvers** [comment]
Love the icon! :+1: Is the kerning in the name on purpose, it looks a bit random :open_mouth:

**Comment by zenangst** [comment]
scatter

Moar float!

**Comment by zenangst** [comment]
@thuygianguyen what do you mean by `bookeh effect`?

**Comment by thuyranosaurus** [comment]
Bokeh

https://www.google.no/search?q=bokeh&client=safari&hl=en&biw=320&bih=460&source=lnms&tbm=isch&sa=X&ei=8F4HVc2qCYa_PKbHgegK&ved=0CAYQ_AUoAQ

-Thuy Gia Nguyen

Designer & Team Leader

 977 35 583

 thuy@hyper.no

**Comment by akamphaug** [comment]
@zenangst I think that looks really good.. 
Two small things.. 
as @timkurvers said kerning is off, "a" and first "t" should be closer to eachother.
Secondly, I would consider moving the big heavy dot to the bottom of the square to make it less visually top heavy.

**Comment by thuyranosaurus** [comment]
@timkurvers. Yeah. The font is buggy when you scale it up to 200 px

-Thuy Gia Nguyen

Designer & Team Leader

 977 35 583

 thuy@hyper.no

**Comment by thuyranosaurus** [comment]
And that is why my Cheesy suggestion was fixed ;)

**Comment by zenangst** [comment]
scatter

**Comment by jgorset** [comment]
Looking good!

**Comment by 3lvis** [comment]
I like where this is going, but I would prefer to keep it more like this layout

[icon] --- [text]

52916a04-cb1a-11e4-8a15-c09307c5e913

**Comment by zenangst** [comment]
I agree with Elvis, having the icon conform to a convention and the ability to add some playful typography  to support it would be ace in my book. Aslo, this kind of logo works best on GitHub which is center stage.

**Comment by thuyranosaurus** [comment]
@zenangst Are people going to see a mushroom? 

@elvis You should only go for one of the styles. Either pictogram with clean text or Scatter with fancy dots. Not both. Confuses people

-Thuy Gia Nguyen

Designer & Team Leader

 977 35 583

 thuy@hyper.no

**Comment by 3lvis** [comment]
@thuygianguyen I didn't meant on going with the tweaked Scatter text, I just meant some simple nice text and the rounded corners square at the left.

**Comment by zenangst** [comment]
@thuygianguyen what's up with you and foods? :sunglasses:

**Comment by jgorset** [comment]
These were the days guys! :D 😍

**Pull request closed without merging**
